<?php
/**
 * UpdatableProduct
 *
 * PHP version 5
 *
 * @category Class
 * @package  DcmApiClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dolead Campaign Manager API v1.0
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DcmModel;

use \ArrayAccess;

/**
 * UpdatableProduct Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     DcmApiClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdatableProduct implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'UpdatableProduct';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'target_margin' => 'double',
        'target_roi' => 'double'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'target_margin' => 'target_margin',
        'target_roi' => 'target_roi'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'target_margin' => 'setTargetMargin',
        'target_roi' => 'setTargetRoi'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'target_margin' => 'getTargetMargin',
        'target_roi' => 'getTargetRoi'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['target_margin'] = isset($data['target_margin']) ? $data['target_margin'] : null;
        $this->container['target_roi'] = isset($data['target_roi']) ? $data['target_roi'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if (!is_null($this->container['target_margin']) && ($this->container['target_margin'] < 0.01)) {
            $invalid_properties[] = "invalid value for 'target_margin', must be bigger than or equal to 0.01.";
        }

        if (!is_null($this->container['target_roi']) && ($this->container['target_roi'] < 0.01)) {
            $invalid_properties[] = "invalid value for 'target_roi', must be bigger than or equal to 0.01.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['target_margin'] < 0.01) {
            return false;
        }
        if ($this->container['target_roi'] < 0.01) {
            return false;
        }
        return true;
    }


    /**
     * Gets target_margin
     * @return double
     */
    public function getTargetMargin()
    {
        return $this->container['target_margin'];
    }

    /**
     * Sets target_margin
     * @param double $target_margin Targeted margin for the product. This value is exclusive with target_roi. If given alone, any previous target roi on the product will be deleted. If given with a target roi, only the target margin will be kept.
     * @return $this
     */
    public function setTargetMargin($target_margin)
    {

        if ($target_margin < 0.01) {
            throw new \InvalidArgumentException('invalid value for $target_margin when calling UpdatableProduct., must be bigger than or equal to 0.01.');
        }
        $this->container['target_margin'] = $target_margin;

        return $this;
    }

    /**
     * Gets target_roi
     * @return double
     */
    public function getTargetRoi()
    {
        return $this->container['target_roi'];
    }

    /**
     * Sets target_roi
     * @param double $target_roi Targeted ROI for the product. This value is exclusive with target_margin. If given alone, any previous target margin on the product will be deleted. If given with a target margin, only the target margin will be kept.
     * @return $this
     */
    public function setTargetRoi($target_roi)
    {

        if ($target_roi < 0.01) {
            throw new \InvalidArgumentException('invalid value for $target_roi when calling UpdatableProduct., must be bigger than or equal to 0.01.');
        }
        $this->container['target_roi'] = $target_roi;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\DcmApiClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\DcmApiClient\ObjectSerializer::sanitizeForSerialization($this));
    }
}


