<?php
/**
 * AdwordsClickRevenue
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dcm
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dolead Campaign Manager API v1.0
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Dcm\Model;

use \ArrayAccess;

/**
 * AdwordsClickRevenue Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Dcm
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdwordsClickRevenue implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'AdwordsClickRevenue';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'conversions_many_per_click' => 'int',
        'conversions_one_per_click' => 'int',
        'gclid' => 'string',
        'revenue' => 'float',
        'transaction_id' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'conversions_many_per_click' => 'conversions_many_per_click',
        'conversions_one_per_click' => 'conversions_one_per_click',
        'gclid' => 'gclid',
        'revenue' => 'revenue',
        'transaction_id' => 'transaction_id'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'conversions_many_per_click' => 'setConversionsManyPerClick',
        'conversions_one_per_click' => 'setConversionsOnePerClick',
        'gclid' => 'setGclid',
        'revenue' => 'setRevenue',
        'transaction_id' => 'setTransactionId'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'conversions_many_per_click' => 'getConversionsManyPerClick',
        'conversions_one_per_click' => 'getConversionsOnePerClick',
        'gclid' => 'getGclid',
        'revenue' => 'getRevenue',
        'transaction_id' => 'getTransactionId'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['conversions_many_per_click'] = isset($data['conversions_many_per_click']) ? $data['conversions_many_per_click'] : null;
        $this->container['conversions_one_per_click'] = isset($data['conversions_one_per_click']) ? $data['conversions_one_per_click'] : null;
        $this->container['gclid'] = isset($data['gclid']) ? $data['gclid'] : null;
        $this->container['revenue'] = isset($data['revenue']) ? $data['revenue'] : null;
        $this->container['transaction_id'] = isset($data['transaction_id']) ? $data['transaction_id'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets conversions_many_per_click
     * @return int
     */
    public function getConversionsManyPerClick()
    {
        return $this->container['conversions_many_per_click'];
    }

    /**
     * Sets conversions_many_per_click
     * @param int $conversions_many_per_click Conversions (many per click) count, for current (gclid, transaction_id)
     * @return $this
     */
    public function setConversionsManyPerClick($conversions_many_per_click)
    {
        $this->container['conversions_many_per_click'] = $conversions_many_per_click;

        return $this;
    }

    /**
     * Gets conversions_one_per_click
     * @return int
     */
    public function getConversionsOnePerClick()
    {
        return $this->container['conversions_one_per_click'];
    }

    /**
     * Sets conversions_one_per_click
     * @param int $conversions_one_per_click Converted clicks (one per click conversions) count, for current (gclid, transaction_id).
     * @return $this
     */
    public function setConversionsOnePerClick($conversions_one_per_click)
    {
        $this->container['conversions_one_per_click'] = $conversions_one_per_click;

        return $this;
    }

    /**
     * Gets gclid
     * @return string
     */
    public function getGclid()
    {
        return $this->container['gclid'];
    }

    /**
     * Sets gclid
     * @param string $gclid Google Click Id
     * @return $this
     */
    public function setGclid($gclid)
    {
        $this->container['gclid'] = $gclid;

        return $this;
    }

    /**
     * Gets revenue
     * @return float
     */
    public function getRevenue()
    {
        return $this->container['revenue'];
    }

    /**
     * Sets revenue
     * @param float $revenue Generated revenue (aggregated for current google click id, if multiple conversions for the same click)
     * @return $this
     */
    public function setRevenue($revenue)
    {
        $this->container['revenue'] = $revenue;

        return $this;
    }

    /**
     * Gets transaction_id
     * @return string
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     * @param string $transaction_id (Optional) a transaction ID (if a click can generate multiple conversions)
     * @return $this
     */
    public function setTransactionId($transaction_id)
    {
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Dcm\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Dcm\ObjectSerializer::sanitizeForSerialization($this));
    }
}


