<?php
/**
 * CampaignQuery
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dcm
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dolead Campaign Manager API v1.0
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Dcm\Model;

use \ArrayAccess;

/**
 * CampaignQuery Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Dcm
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignQuery implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'CampaignQuery';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'account' => 'string',
        'account_name' => 'string',
        'account_publisher_id' => 'string',
        'advertiser' => 'string',
        'base_campaign' => 'string',
        'campaign_type' => 'string',
        'id' => '\Dcm\Model\TextParameter',
        'name' => '\Dcm\Model\TextParameter',
        'publisher' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'account' => 'account',
        'account_name' => 'account_name',
        'account_publisher_id' => 'account_publisher_id',
        'advertiser' => 'advertiser',
        'base_campaign' => 'base_campaign',
        'campaign_type' => 'campaign_type',
        'id' => 'id',
        'name' => 'name',
        'publisher' => 'publisher'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'account' => 'setAccount',
        'account_name' => 'setAccountName',
        'account_publisher_id' => 'setAccountPublisherId',
        'advertiser' => 'setAdvertiser',
        'base_campaign' => 'setBaseCampaign',
        'campaign_type' => 'setCampaignType',
        'id' => 'setId',
        'name' => 'setName',
        'publisher' => 'setPublisher'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'account' => 'getAccount',
        'account_name' => 'getAccountName',
        'account_publisher_id' => 'getAccountPublisherId',
        'advertiser' => 'getAdvertiser',
        'base_campaign' => 'getBaseCampaign',
        'campaign_type' => 'getCampaignType',
        'id' => 'getId',
        'name' => 'getName',
        'publisher' => 'getPublisher'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const CAMPAIGN_TYPE_SEARCH = 'SEARCH';
    const CAMPAIGN_TYPE_DISPLAY = 'DISPLAY';
    const CAMPAIGN_TYPE_SHOPPING = 'SHOPPING';
    const PUBLISHER_GOOGLE = 'GOOGLE';
    const PUBLISHER_BING = 'BING';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getCampaignTypeAllowableValues()
    {
        return [
            self::CAMPAIGN_TYPE_SEARCH,
            self::CAMPAIGN_TYPE_DISPLAY,
            self::CAMPAIGN_TYPE_SHOPPING,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getPublisherAllowableValues()
    {
        return [
            self::PUBLISHER_GOOGLE,
            self::PUBLISHER_BING,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['account'] = isset($data['account']) ? $data['account'] : null;
        $this->container['account_name'] = isset($data['account_name']) ? $data['account_name'] : null;
        $this->container['account_publisher_id'] = isset($data['account_publisher_id']) ? $data['account_publisher_id'] : null;
        $this->container['advertiser'] = isset($data['advertiser']) ? $data['advertiser'] : null;
        $this->container['base_campaign'] = isset($data['base_campaign']) ? $data['base_campaign'] : null;
        $this->container['campaign_type'] = isset($data['campaign_type']) ? $data['campaign_type'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['publisher'] = isset($data['publisher']) ? $data['publisher'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array("SEARCH", "DISPLAY", "SHOPPING", "NATIVE", "MULTI_CHANNEL");
        if (!in_array($this->container['campaign_type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'campaign_type', must be one of #{allowed_values}.";
        }

        $allowed_values = array("GOOGLE", "BING");
        if (!in_array($this->container['publisher'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'publisher', must be one of #{allowed_values}.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array("SEARCH", "DISPLAY", "SHOPPING", "NATIVE", "MULTI_CHANNEL");
        if (!in_array($this->container['campaign_type'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("GOOGLE", "BING");
        if (!in_array($this->container['publisher'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets account
     * @return string
     */
    public function getAccount()
    {
        return $this->container['account'];
    }

    /**
     * Sets account
     * @param string $account ID of the account in Dolead system.
     * @return $this
     */
    public function setAccount($account)
    {
        $this->container['account'] = $account;

        return $this;
    }

    /**
     * Gets account_name
     * @return string
     */
    public function getAccountName()
    {
        return $this->container['account_name'];
    }

    /**
     * Sets account_name
     * @param string $account_name Name account in Dolead system.
     * @return $this
     */
    public function setAccountName($account_name)
    {
        $this->container['account_name'] = $account_name;

        return $this;
    }

    /**
     * Gets account_publisher_id
     * @return string
     */
    public function getAccountPublisherId()
    {
        return $this->container['account_publisher_id'];
    }

    /**
     * Sets account_publisher_id
     * @param string $account_publisher_id ID of the account in Publisher network.
     * @return $this
     */
    public function setAccountPublisherId($account_publisher_id)
    {
        $this->container['account_publisher_id'] = $account_publisher_id;

        return $this;
    }

    /**
     * Gets advertiser
     * @return string
     */
    public function getAdvertiser()
    {
        return $this->container['advertiser'];
    }

    /**
     * Sets advertiser
     * @param string $advertiser ID of the advertiser in Dolead system.
     * @return $this
     */
    public function setAdvertiser($advertiser)
    {
        $this->container['advertiser'] = $advertiser;

        return $this;
    }

    /**
     * Gets base_campaign
     * @return string
     */
    public function getBaseCampaign()
    {
        return $this->container['base_campaign'];
    }

    /**
     * Sets base_campaign
     * @param string $base_campaign A trial campaign's link to the base campaign.
     * @return $this
     */
    public function setBaseCampaign($base_campaign)
    {
        $this->container['base_campaign'] = $base_campaign;

        return $this;
    }

    /**
     * Gets campaign_type
     * @return string
     */
    public function getCampaignType()
    {
        return $this->container['campaign_type'];
    }

    /**
     * Sets campaign_type
     * @param string $campaign_type Filter over the campaign type
     * @return $this
     */
    public function setCampaignType($campaign_type)
    {
        $allowed_values = array('SEARCH', 'DISPLAY', 'SHOPPING', 'NATIVE', 'MULTI_CHANNEL');
        if (!in_array($campaign_type, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'campaign_type', must be one of 'SEARCH', 'DISPLAY', 'SHOPPING'");
        }
        $this->container['campaign_type'] = $campaign_type;

        return $this;
    }

    /**
     * Gets id
     * @return \Dcm\Model\TextParameter
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param \Dcm\Model\TextParameter $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     * @return \Dcm\Model\TextParameter
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param \Dcm\Model\TextParameter $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets publisher
     * @return string
     */
    public function getPublisher()
    {
        return $this->container['publisher'];
    }

    /**
     * Sets publisher
     * @param string $publisher Filter over the campaign publisher network
     * @return $this
     */
    public function setPublisher($publisher)
    {
        $allowed_values = array('GOOGLE', 'BING');
        if (!in_array($publisher, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'publisher', must be one of 'GOOGLE', 'BING'");
        }
        $this->container['publisher'] = $publisher;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Dcm\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Dcm\ObjectSerializer::sanitizeForSerialization($this));
    }
}


