<?php
/**
 * CallsStatisticTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dcm
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dolead Campaign Manager API v1.0
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Dcm;

/**
 * CallsStatisticTest Class Doc Comment
 *
 * @category    Class */
// * @description CallsStatistic
/**
 * @package     Dcm
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CallsStatisticTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CallsStatistic"
     */
    public function testCallsStatistic()
    {

    }

    /**
     * Test attribute "account_publisher_id"
     */
    public function testPropertyAccountPublisherId()
    {

    }

    /**
     * Test attribute "calls"
     */
    public function testPropertyCalls()
    {

    }

    /**
     * Test attribute "calls_cost"
     */
    public function testPropertyCallsCost()
    {

    }

    /**
     * Test attribute "calls_duration"
     */
    public function testPropertyCallsDuration()
    {

    }

    /**
     * Test attribute "campaign_publisher_id"
     */
    public function testPropertyCampaignPublisherId()
    {

    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {

    }

}
