<?php
/**
 * ProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dcm
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dolead Campaign Manager API v1.0
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Dcm;

/**
 * ProductTest Class Doc Comment
 *
 * @category    Class */
// * @description Product
/**
 * @package     Dcm
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Product"
     */
    public function testProduct()
    {

    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {

    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {

    }

    /**
     * Test attribute "account_publisher_id"
     */
    public function testPropertyAccountPublisherId()
    {

    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {

    }

    /**
     * Test attribute "category_l1"
     */
    public function testPropertyCategoryL1()
    {

    }

    /**
     * Test attribute "category_l2"
     */
    public function testPropertyCategoryL2()
    {

    }

    /**
     * Test attribute "category_l3"
     */
    public function testPropertyCategoryL3()
    {

    }

    /**
     * Test attribute "category_l4"
     */
    public function testPropertyCategoryL4()
    {

    }

    /**
     * Test attribute "category_l5"
     */
    public function testPropertyCategoryL5()
    {

    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {

    }

    /**
     * Test attribute "custom_attribute_0"
     */
    public function testPropertyCustomAttribute0()
    {

    }

    /**
     * Test attribute "custom_attribute_1"
     */
    public function testPropertyCustomAttribute1()
    {

    }

    /**
     * Test attribute "custom_attribute_2"
     */
    public function testPropertyCustomAttribute2()
    {

    }

    /**
     * Test attribute "custom_attribute_3"
     */
    public function testPropertyCustomAttribute3()
    {

    }

    /**
     * Test attribute "custom_attribute_4"
     */
    public function testPropertyCustomAttribute4()
    {

    }

    /**
     * Test attribute "device"
     */
    public function testPropertyDevice()
    {

    }

    /**
     * Test attribute "product_type_l1"
     */
    public function testPropertyProductTypeL1()
    {

    }

    /**
     * Test attribute "product_type_l2"
     */
    public function testPropertyProductTypeL2()
    {

    }

    /**
     * Test attribute "product_type_l3"
     */
    public function testPropertyProductTypeL3()
    {

    }

    /**
     * Test attribute "product_type_l4"
     */
    public function testPropertyProductTypeL4()
    {

    }

    /**
     * Test attribute "product_type_l5"
     */
    public function testPropertyProductTypeL5()
    {

    }

    /**
     * Test attribute "publisher"
     */
    public function testPropertyPublisher()
    {

    }

    /**
     * Test attribute "publisher_id"
     */
    public function testPropertyPublisherId()
    {

    }

    /**
     * Test attribute "target_margin"
     */
    public function testPropertyTargetMargin()
    {

    }

    /**
     * Test attribute "target_roi"
     */
    public function testPropertyTargetRoi()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

}
